################################################################################
# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

class-attrs-all:
  pre-cluster-threshold: 0.21666836936549047
  nms-iou-threshold: 0.5645207000469065
  minBoxes: 2
  dbscan-min-score: 0.693671458753017
  eps: 0.15584185873130887
  detected-min-w: 20
  detected-min-h: 20
class-attrs-1:
  pre-cluster-threshold: 999
class-attrs-2:
  pre-cluster-threshold: 999
property:
  cluster-mode: 3
  gie-unique-id: 1
  gpu-id: 0
  infer-dims: 3;544;960
  interval: 1
  labelfile-path: ds-detector-labels.txt
  maintain-aspect-ratio: 1
  model-color-format: 0
  net-scale-factor: 0.003921569790691137
  network-mode: 1
  model-engine-file: /opt/storage/resnet34_peoplenet_int8.etlt_b10_gpu0_int8.engine
  tlt-encoded-model: /opt/storage/resnet34_peoplenet_int8.etlt
  int8-calib-file: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-fewshot-learning-app/models/mtmc/resnet34_peoplenet_int8.txt
  num-detected-classes: 3
  output-blob-names: output_bbox/BiasAdd;output_cov/Sigmoid
  process-mode: 1
  tlt-model-key: tlt_encode
  uff-input-blob-name: input_1
